#!/usr/bin/env python

import os
import sys
import json
import boto3

# Check the version is Python 3.6+
assert sys.version_info.major >= 3 and sys.version_info.minor >= 6, \
    "Python 3.6+ required."

# Get the deployment label.
if len(sys.argv) != 2:
    raise ValueError(f"Wrong number of arguments ({len(sys.argv)}): {sys.argv}")
label = sys.argv[-1]

# Load the config file for the s3 bucket and prefix.
with open('deployment_config.json', 'r') as f:
    conf = json.load(f)
root = conf['root']
prefix = root['prefix'] + label

# Check that we're doing the right thing.
s3_path = f"{root['bucket']}/{prefix}"

print(f"The following files will be pushed to 's3://{s3_path}' "
      f"(they will be PUBLIC):")
for fname in os.listdir('dist'):
    print('\t', os.path.join('dist', fname))
res = input("Continue (Y/n)?")

if res.lower() != 'y' and res != '':
    print("Aborting.")
    sys.exit()

# Push the files.
s3 = boto3.client('s3')

for fname in os.listdir('dist'):
    fpath = os.path.join('dist', fname)
    print(f"Putting {fpath} -> s3://{s3_path}/{fname}")
    s3.upload_file(os.path.join('dist', fname), root['bucket'],
                   f'{prefix}/{fname}', ExtraArgs={'ACL': 'public-read'})
